# Generated by Django 4.1.7 on 2023-03-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
    ]
